### ISSUE TITLE
Bandwidth Consumptiom

### ISSUE THREAD

**Issue by catalitico** [arut/nginx-rtmp-module#1063]
This might seem a stupid question but i rather ask stupid questions than not knowing anything.

What is the estimate Bandwidth consumption for nginx, as for incoming with a single encoder at 1.2 mbps?

Say i want to have 8 encoders. Now whenever i start the service the incoming traffic goes to 5.mbps? no matter if i have one or the 8 encoders broadcasting.. as soon as live is on.. it goes to those values.

What am i not considering in my estimations? or what should be the expected consumption just on our side from our encoders?

**Comment by eutychus** [comment]
The incoming bandwidth will be whatever the encoder is sending... depending on the encoder, there may be differences in how variable the encode rate is... some are constant, some use a fairly large VBV buffer, others give options as to how to handle the encode.  A general rule of thumb if you are running into problems streaming over the public internet, is that you want at least 50% more available bandwidth than what your advertised rates are, in order to deal with variations in bit rate from the encoder, as well as network quality issues.

**Comment by catalitico** [comment]
Ok but, see whenever i start the service... i tried starting it with "hls off". Just did one encoder and switched it to on... and it showed the incoming traffic as 5mbps (from the encoders... for the moment... either 1 or 8 show as consuming that much of incoming traffic because i have a 5mbps limit).

I don't know what's going on :(

**Comment by catalitico** [comment]
I checked that my encoders were sending over 3mb.... so i will close the issue
