### ISSUE TITLE
Add delay to stream

### ISSUE THREAD

**Issue by sistason** [arut/nginx-rtmp-module#558]
Hey,

lots of talk about minimising delay in the stream.

Can you ADD delay to a stream, e.g. a big buffer and make sure input was at least $time delayed?

Usage: Game-Streams often need delay to prevent cheating, and a delay on the streamcreator-machine could lead to lost video when the recorder crashes or the streaming-software is buggy.

**Comment by ubuntuaddicted** [comment]
The delay is done at the streamers level. That's how I handle it anyway. I have a dedicated streaming Nginx server in my LAN that I use but currently it only pushes the stream. So I handle the delay in OBS.

**Comment by sistason** [comment]
Yes, I currently handle the delay in OBS, also. But, as it sometimes crashes and often reconnects (with a lossy connection), the delayed content sometimes gets lost. This leads to a downtime of 2*delay, which I seek to avoid.

Is there a way to handle delay in nginx-rtmp? exec a sleep-file on reconnect/play, extra option, encoding with passthrough options and calling sleep from ffmpeg, something?

**Comment by ubuntuaddicted** [comment]
well sure, if you really need a delay at the nginx level and the current nginx and rtmp module doesn't provide that search around for a developer that would help to make this happen if you really want this to happen. this is an open source project, meaning anyone can help improve it. or use ffmpeg to transcode your videos before pushing them out which would clearly add that delay you're looking for just as a consequence of ffmpeg transcoding. (this is just my opinion)

**Comment by sistason** [comment]
I now did something similar, I used nginx-record to buffer the stream locally and exec_publish to start a python-script which publishes the file back to nginx again, after a certain delay.
Closed, with reference to https://github.com/sistason/rtmp_stream_delayer, where I uploaded my setup to delay a rtmp-stream a specified time.

**Comment by refriedfood** [comment]
This doesn't really answer whether or not you can add a buffer in nginx so that whomever is publishing the stream to the server, packets are not lost from the server to the viewer - which is the reason. I don't want a delay for any other reason than to buffer to make sure the viewer isn't dropping packets due to the nginx server - as I know the source is not dropping, but when you check it on another source, packets are obviously being lost from server to client. The best way to prevent this is some sort of connection buffering from server to client.
